name: go-build

on:
  push:
    branches-ignore: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build
      run: CGO_ENABLED=0 go build -v -o ./bin/version-checker ./cmd/.

    - name: Test
      run: go test -v ./...
